version: "2.1"

services:
  mockdata:
    build: ./mockdata
    entrypoint: "go run main.go"
    depends_on:
      - redis

  sales:
    depends_on:
      - logs
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - api_name=sales
        

  currency_conversions:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        - api_name=currency_conversions

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://currency_conversions:8080/check/currency_conversions/ping" ]
      interval: 10s
      timeout: 1.5s
      retries: 5

  items:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - api_name=items

    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://items:8080/check/items/ping" ]
      interval: 10s
      timeout: 1s
      retries: 5

  sold_items:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - api_name=sold_items

    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://sold_items:8080/check/sold_items/ping" ]
      interval: 10s
      timeout: 1s
      retries: 5

  users:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        - api_name=users

    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://users:8080/check/users/ping"]
      interval: 10s
      timeout: 1s
      retries: 5

  logs:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - api_name=logs

    depends_on:
      - redis
    volumes: 
      - ./logs/topics.cfg:/app/topics.cfg:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://logs:8080/check/pubsub/ping" ]
      interval: 10s
      timeout: 1s
      retries: 5
    environment:
      config_path: /app/topics.cfg

  front:
    build: ./nginx/
    ports:
      - 8080:80
    volumes: 
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx2.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      items:
        condition: service_healthy
      sold_items:
        condition: service_healthy
      users:
        condition: service_healthy
      currency_conversions:
        condition: service_healthy
      logs:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--bind", "redis", "--port", "6379" ]
    ports:
    - 6379:6379